name: Deploy Quantum Coinflip

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python (match Lambda runtime)
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Deploy Frontend to S3
      - name: Deploy Frontend to S3
        run: |
          aws s3 sync ./frontend/ s3://quantum-coinflip-frontend --delete

      # Build and Deploy Backend to Lambda via S3
      - name: Build and Deploy Lambda
        run: |
          # Create a clean directory for the Lambda package
          mkdir -p lambda_package
          cp backend/lambda_function.py lambda_package/
          cd lambda_package
          # Install minimal dependencies
          pip install amazon-braket-sdk --no-deps -t .
          pip install boto3 -t .
          # Zip the package
          zip -r ../lambda.zip .
          # Check size (for debugging)
          ls -lh ../lambda.zip
          du -sh .
          # Upload to S3
          aws s3 cp ../lambda.zip s3://quantum-coinflip-lambda-deploy/lambda.zip
          # Update Lambda function code from S3
          aws lambda update-function-code \
            --function-name quantumCoinflip \
            --s3-bucket quantum-coinflip-lambda-deploy \
            --s3-key lambda.zip

      # Output the API URL
      - name: Output API URL
        run: |
          echo "API URL: https://rs87korb72.execute-api.us-east-1.amazonaws.com/prod/flip"